flowchart TD
codemyspeccli_hooks[CodeMySpecCli.Hooks]
codemyspeccli_terminalpanes[CodeMySpecCli.TerminalPanes]
storiesserver[StoriesServer]
codemyspeccli_webserver[CodeMySpecCli.WebServer]
analyticsadminserver[AnalyticsAdminServer]
codemyspeccli[CodeMySpecCli]
componentsserver[ComponentsServer]
codemyspeccli_scope[CodeMySpecCli.Scope]
codemyspeccli_application[CodeMySpecCli.Application]
codemyspeccli_cli[CodeMySpecCli.Cli]
stories_storiesmapper[Stories.StoriesMapper]
components_componentsmapper[Components.ComponentsMapper]
validators[Validators]
formatters[Formatters]
codemyspeccli_clirunner[CodeMySpecCli.CliRunner]
codemyspeccli_config[CodeMySpecCli.Config]